baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Portafolio'
theme = 'ananke'

[params]
text_color = "black"
author = "Diego Manzo Escalante"
site_logo = "logo.png"
description = "Practicas Diego Manzo Escalante"
background_color_class = "bg-dark-green"